(defun is-palindrome (input)
  (let ((clean-input (string-downcase (string input))))
    (equal clean-input (reverse clean-input))))
(defun run-palindrome-check ()
  (format t "~%Enter a word to check: ")
  (finish-output)
  (let ((user-word (read-line)))
    (if (is-palindrome user-word)
        (format t "Yes! '~A' is a palindrome.~%" user-word)
        (format t "No, '~A' is not a palindrome.~%" user-word)))
  (values))